name: Rename Folder

on:
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rename folder
        run: |
          git mv "icon-DiktaTV" "opale"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Rename icon-DiktaTV to opale"
          git push
